name: Deploy Python App to Azure Web App - AppRecom

# Déclenche le workflow à chaque push sur la branche main
on:
  push:
    branches:
      - main
  workflow_dispatch:  # permet de lancer manuellement depuis GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - uses: actions/checkout@v3

      # 2️⃣ Installer Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Installer les dépendances Python
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 5️⃣ Déployer sur Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppRecom'    # Nom de ton App Service
          slot-name: 'Production'
          package: '.'
